# Generated by Django 3.2 on 2022-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('W', '여자'), ('M', '남자')], max_length=20),
        ),
    ]
