# Generated by Django 3.2 on 2022-06-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('W', '여자')], max_length=20),
        ),
    ]
