# Generated by Django 3.2 on 2022-06-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apt_name', models.CharField(max_length=300)),
                ('apt_dong', models.CharField(max_length=30, null=True)),
                ('apt_transaction_type', models.CharField(max_length=15)),
                ('apt_price', models.CharField(max_length=300)),
                ('apt_category', models.CharField(max_length=15)),
                ('apt_flat', models.FloatField()),
                ('apt_real_flat', models.FloatField()),
                ('apt_height', models.CharField(max_length=50, null=True)),
                ('apt_wind', models.CharField(max_length=30, null=True)),
                ('apt_comment', models.TextField(null=True)),
                ('apt_feature', models.TextField(null=True)),
                ('apt_confirm', models.CharField(max_length=50)),
                ('apt_confirm_date', models.DateField()),
                ('apt_link', models.URLField(blank=True, max_length=500, null=True)),
                ('apt_regiseter', models.DateTimeField(null=True)),
                ('apt_change_price', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
