# Generated by Django 3.2 on 2022-06-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_rename_location_id_apartment_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-id'], 'verbose_name': '아파트', 'verbose_name_plural': '아파트 목록'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id'], 'verbose_name': '위치', 'verbose_name_plural': '위치 목록'},
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='apt_regiseter',
            new_name='apt_register',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
    ]
