# Generated by Django 3.2 on 2022-06-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_apartment_apt_confirm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apt_confirm_date',
            field=models.DateField(),
        ),
    ]
