# Generated by Django 3.2 on 2022-06-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_apartment_apt_confirm_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['id'], 'verbose_name': '아파트', 'verbose_name_plural': '아파트 목록'},
        ),
    ]
